name: bioio_bioformats
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - numpy
  - tifffile>=2024.1.30
  - scyjava  # Provides Java/Maven for Bio-Formats
  - pip
  - pip:
    - bioio
    - bioio-bioformats
    - bioio-tifffile
    - bioio-ome-tiff
